version: "3"

services:
    nodejs-linkapi:
        build:
            context: .
            dockerfile: Dockerfile
        image: nodejs
        container_name: nodejs-linkapi
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_USERNAME=$MONGO_USERNAME
            - MONGO_PASSWORD=$MONGO_PASSWORD
            - MONGO_HOSTNAME=$MONGO_HOSTNAME
            - MONGO_PORT=$MONGO_PORT
            - MONGO_DB=$MONGO_DB
        ports:
            - "8080:8080"
        volumes:
            - .:/home/node/app
            - node_modules:/home/node/app/node_modules
        networks:
            - app-network
        command: /home/node/app/node_modules/.bin/ts-node-dev --respawn --transpile-only source/index.ts
    mongodb-linkapi:
        image: mongo:4.1.8-xenial
        container_name: mongodb-linkapi
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        volumes:
            - dbdata:/data/mongodb
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    dbdata:
    node_modules:
